// John M. Singleton and Ryan Steenson
// HW2.java finished R 2/7/2019
// CSCI 476 - Computer Security
// HW2 due 2/7/2019 by 11:30 PM

import java.io.*;
import java.util.*;
import java.util.Scanner;

class HW2
{
	public static void main(String[] args)
	{
		String kouros = null;  // The name is not relevant.  It's just a recent addition to my vocabulary.
		try
		{
			String oneLine = null;
			Scanner fileIn = new Scanner( new FileReader( "memorydump.dmp" ) );
			while( fileIn.hasNextLine( ) )
			{
				oneLine = fileIn.nextLine( );
				//System.out.println( oneLine + "***NEW     LINE***" );
				kouros = kouros + oneLine;
				//System.out.println(kouros.length());
			}
		}
		catch( IOException e )
		{
			System.out.println( e );
		}
		
		// The desired credit card information can be obtained by examining the output generated by
		// by line 21.  Now we just make looking for the pattern that we identified a part of our
		// program and generate nice output
		List<CreditCardInfo> records = new ArrayList<CreditCardInfo>();
		
		for(int i = 0; i < kouros.length(); i++)
		{
			if(kouros.charAt(i) == '^')
			{
			    //System.out.println("Getty1");
				int j = i + 1;
				String last_name = "";
				while( ((int) kouros.charAt(j) > 64 && (int) kouros.charAt(j) < 91) || ((int) kouros.charAt(j) > 96 && (int) kouros.charAt(j) < 123) )
				{
					last_name = last_name + kouros.charAt(j);
					j++;
				}
				if(kouros.charAt(j) == '/')
				{
				    //System.out.println("Getty2");
					j = j + 1;
					String first_name = "";
					while( ((int) kouros.charAt(j) > 64 && (int) kouros.charAt(j) < 91) || ((int) kouros.charAt(j) > 96 && (int) kouros.charAt(j) < 123) )
					{
						first_name = first_name + kouros.charAt(j);
						j++;
					}
					// If the pattern "^[stuff]/[stuff]^" is encountered, then our program assumes
					// that a record has been found.
					if(kouros.charAt(j) == '^')
					{
						//System.out.println("Getty3");
						CreditCardInfo record = new CreditCardInfo();
						// We should make these fields private in the CreditCardInfo class and add get and set methods.
						record.name = last_name + first_name;
						record.card_number = kouros.substring(i-16, i);
						//System.out.println("Getty4:  " + record.name);
						record.expiration_date = kouros.substring(i+record.name.length()+3, i+record.name.length()+7);
						record.cvc_number = kouros.substring(i+record.name.length()+7, i+record.name.length()+10);
						records.add(record);
					}
				}
			}
		}
		
		// Generate the nice output.
		PrintWriter fileOut = null;
		try
		{
			fileOut = new PrintWriter( new FileWriter("HW2.output") );
			fileOut.println("There are " + records.size() + " track I records in the memory data.");  // If there's only 1, then this will currently output shitty English.
			for(int i = 0; i < records.size(); i++)
			{
				CreditCardInfo record = records.get(i);
				int j = i + 1;
				fileOut.println("Record " + j + " info:");
				fileOut.println("Cardholder's Name:  " + record.name);
				fileOut.println("Credit Card Number:  " + record.card_number);
				fileOut.println("Expiration Date:  " + record.expiration_date.substring(2, 4) + "/" + record.expiration_date.substring(0, 2));
				fileOut.println("CVC Number:  " + record.cvc_number);
			
			}
		}
		catch( IOException e )
		{ e.printStackTrace(); }
		if( fileOut != null )
			fileOut.close();
		//System.out.println("We have " + records.size() + " records.");
		//System.out.println(records.get(0).expiration_date);
	}
}

class CreditCardInfo
{
	public String name = "";
    public String card_number = "";
	public String expiration_date = "";
	public String cvc_number = "";
}